"""empty message

Revision ID: 15d0aeac6b97
Revises: 604fff887172
Create Date: 2022-09-19 17:41:59.588390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d0aeac6b97'
down_revision = '604fff887172'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('players_games_player_id_fkey', 'players_games', type_='foreignkey')
    op.create_foreign_key(None, 'players_games', 'players', ['player_id'], ['vk_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players_games', type_='foreignkey')
    op.create_foreign_key('players_games_player_id_fkey', 'players_games', 'players', ['player_id'], ['id'])
    # ### end Alembic commands ###
