"""empty message

Revision ID: 39648866af85
Revises: ec15c02eabb1
Create Date: 2022-09-21 12:30:02.946902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39648866af85'
down_revision = 'ec15c02eabb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_answers',
    sa.Column('answers_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answers_id'], ['answers.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('answers_id', 'game_id')
    )
    op.drop_constraint('games_answers_right_id_fkey', 'games', type_='foreignkey')
    op.drop_column('games', 'answers_right_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('answers_right_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('games_answers_right_id_fkey', 'games', 'answers', ['answers_right_id'], ['id'])
    op.drop_table('games_answers')
    # ### end Alembic commands ###
