"""empty message

Revision ID: 5d9da5ca6b43
Revises: bbd5e897ca8a
Create Date: 2022-09-20 09:27:23.006098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9da5ca6b43'
down_revision = 'bbd5e897ca8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('rating', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'question_id')
    op.drop_column('answers', 'rating')
    # ### end Alembic commands ###
