"""empty message

Revision ID: 604fff887172
Revises: c4d3eba2d42f
Create Date: 2022-09-19 10:49:25.712181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604fff887172'
down_revision = 'c4d3eba2d42f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('is_run', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'is_run')
    # ### end Alembic commands ###
