"""empty message

Revision ID: 7a9da6b21435
Revises: 5d9da5ca6b43
Create Date: 2022-09-20 11:57:24.143186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9da6b21435'
down_revision = '5d9da5ca6b43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
