"""empty message

Revision ID: 924414ab8882
Revises: 7a9da6b21435
Create Date: 2022-09-20 12:02:05.048814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924414ab8882'
down_revision = '7a9da6b21435'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
