"""empty message

Revision ID: bbd5e897ca8a
Revises: 15d0aeac6b97
Create Date: 2022-09-19 21:08:28.061772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd5e897ca8a'
down_revision = '15d0aeac6b97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
