"""empty message

Revision ID: ec15c02eabb1
Revises: 40ccd01c7ce1
Create Date: 2022-09-21 11:32:18.600579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec15c02eabb1'
down_revision = '40ccd01c7ce1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('answers_right_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'answers', ['answers_right_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'answers_right_id')
    # ### end Alembic commands ###
